# -*- coding: utf-8 -*-
"""
Expedition E19: reconnaissance of the equivalent quasivariety.

ZTL is algebraizable (E14); its equivalent algebraic semantics is the
quasivariety generated by the three-element algebra
A = ({T,F,Z}; ¬,∧,∨,→,⊕,↔). Before deciding whether the structure
theory deserves a separate paper (curator's call), we scout the ground:

  1. SUBALGEBRAS of A — expect exactly the Boolean core {T,F} and A.
  2. CONGRUENCES of A — the measurement CORRECTED the guess: A is NOT
     simple. The partition {T,F}|{Z} is a congruence — and it is
     exactly the GREEDINESS KERNEL (no operation ever outputs Z, so
     "collapse the classicals" is compatible). The congruence lattice
     is the three-chain Δ < θ_Z < ∇: A is SUBDIRECTLY IRREDUCIBLE with
     monolith θ_Z — greediness is not just a theorem about A, it IS
     A's monolith.
  3. THE CLONE THEOREM, measured exactly: the term operations of A are
     precisely the projections plus ALL external functions
     (unary: 1 + 8; binary: 2 + 512) — expressive completeness (E14)
     upgraded to a clone-level identity.
  4. THE PLONKA PROBE — the decisive structural discriminator. Bochvar
     algebras (Bonzio–Pra Baldi 2024) live over Plonka sums, and Plonka
     sums of Boolean algebras satisfy every REGULAR Boolean identity
     (same variables on both sides). ZTL's greedy algebra FAILS the
     regular identity p∧p = p — so A is NOT a Plonka sum of Boolean
     algebras: the greedy quasivariety is structurally foreign to the
     weak-Kleene/BCA landscape, not a notational variant of it.
"""

from itertools import product

from ztl import T, F, Z, VALUES, NOT, OPS2

OPS1 = {"not": NOT}


# --------------------------------------------------------- 1. subalgebras
def subalgebras():
    subs = []
    universe = list(VALUES)
    for mask in range(1, 8):
        S = [v for i, v in enumerate(universe) if mask >> i & 1]
        ok = all(NOT(a) in S for a in S) and \
            all(op(a, b) in S for op in OPS2.values() for a in S for b in S)
        if ok:
            subs.append(S)
    return subs


# --------------------------------------------------------- 2. congruences
PARTITIONS = [
    ("identity", {T: 0, F: 1, Z: 2}),
    ("{T,F}|{Z}", {T: 0, F: 0, Z: 1}),
    ("{T,Z}|{F}", {T: 0, F: 1, Z: 0}),
    ("{F,Z}|{T}", {T: 0, F: 1, Z: 1}),
    ("all-in-one", {T: 0, F: 0, Z: 0}),
]


def is_congruence(cls):
    for a, a2 in product(VALUES, repeat=2):
        if cls[a] != cls[a2]:
            continue
        if cls[NOT(a)] != cls[NOT(a2)]:
            return False
        for b, b2 in product(VALUES, repeat=2):
            if cls[b] != cls[b2]:
                continue
            for op in OPS2.values():
                if cls[op(a, b)] != cls[op(a2, b2)]:
                    return False
    return True


# ------------------------------------------------------ 3. clone closure
def close_clone(arity):
    """All term operations of the given arity, by closure from
    projections under the fundamental operations."""
    points = list(product(VALUES, repeat=arity))
    projs = [tuple(pt[i] for pt in points) for i in range(arity)]
    clone = set(projs)
    frontier = list(clone)
    while frontier:
        new = set()
        current = list(clone)
        for f in frontier:
            g = tuple(NOT(x) for x in f)
            if g not in clone:
                new.add(g)
        for f in frontier:
            for g in current:
                for op in OPS2.values():
                    for h in (tuple(op(a, b) for a, b in zip(f, g)),
                              tuple(op(b, a) for a, b in zip(f, g))):
                        if h not in clone:
                            new.add(h)
        clone |= new
        frontier = list(new)
    return clone, projs, points


def external(fn):
    return all(v in (T, F) for v in fn)


# ------------------------------------------------------- 4. Plonka probe
REGULAR_BOOLEAN_IDENTITIES = [
    # (name, lhs, rhs) — regular: same variables on both sides;
    # every Plonka sum of Boolean algebras satisfies ALL of these.
    ("idempotence ∧      p∧p = p",
     lambda p: OPS2["and"](p, p), lambda p: p),
    ("idempotence ∨      p∨p = p",
     lambda p: OPS2["or"](p, p), lambda p: p),
    ("double negation    ¬¬p = p",
     lambda p: NOT(NOT(p)), lambda p: p),
]


if __name__ == "__main__":
    print("=" * 72)
    print("E19. THE QUASIVARIETY, SCOUTED: WHAT A SEPARATE PAPER WOULD MINE")
    print("=" * 72)

    print("\n### 1. Subalgebras of A = ({T,F,Z}; the six connectives)")
    subs = subalgebras()
    for S in subs:
        tag = "the Boolean core" if len(S) == 2 else "A itself"
        print(f"  {{{', '.join(S)}}} — {tag}")
    print(f"  exactly {len(subs)}: the classical world sits inside as the"
          f" unique proper subalgebra (C-extension, algebraically)")

    print("\n### 2. Congruences of A")
    congs = [(nm, cls) for nm, cls in PARTITIONS if is_congruence(cls)]
    for nm, _ in congs:
        print(f"  ✓ {nm}")
    for nm, _ in PARTITIONS:
        if nm not in [c[0] for c in congs]:
            print(f"  ✗ {nm} — not compatible")
    chain3 = len(congs) == 3 and "{T,F}|{Z}" in [c[0] for c in congs]
    print("  ⟹ A is NOT simple — and the unique proper congruence is the")
    print("  GREEDINESS KERNEL θ_Z = {T,F}|{Z}: compatibility of θ_Z is")
    print("  exactly the statement that no operation ever outputs Z.")
    print("  Congruence lattice = the chain Δ < θ_Z < ∇ ⟹ A is")
    print("  SUBDIRECTLY IRREDUCIBLE with monolith θ_Z.")
    cls = dict(PARTITIONS)["{T,F}|{Z}"]
    outs = {OPS2[o](a, b) for o in OPS2 for a in VALUES for b in VALUES}
    outs |= {NOT(a) for a in VALUES}
    print(f"  quotient A/θ_Z: two elements, every operation lands in the")
    print(f"  classical class (operation outputs ⊆ {{T,F}}: "
          f"{sorted(outs) == ['F', 'T']}) — the mark evaporates, "
          f"algebraically.")

    print("\n### 3. The clone theorem (measured exactly)")
    c1, p1, _ = close_clone(1)
    ext1 = sum(1 for f in c1 if external(f))
    print(f"  unary term operations: {len(c1)}"
          f" = {len(p1)} projection + {ext1} external"
          f" ({'✓ = 1 + 8, ALL externals' if len(c1) == 9 and ext1 == 8 else '✗'})")
    c2, p2, _ = close_clone(2)
    ext2 = sum(1 for f in c2 if external(f))
    proj2 = sum(1 for f in c2 if f in p2)
    print(f"  binary term operations: {len(c2)}"
          f" = {proj2} projections + {ext2} external"
          f" ({'✓ = 2 + 512, ALL externals' if len(c2) == 514 and ext2 == 512 else '✗'})")
    print("  CLONE THEOREM: term operations = projections ∪ all external")
    print("  functions — E14's expressive completeness, now exact at clone")
    print("  level (nothing else sneaks in: no function ever outputs Z).")

    print("\n### 4. The Plonka probe (the structural discriminator)")
    print("  Plonka sums of Boolean algebras satisfy every REGULAR Boolean")
    print("  identity; Bochvar algebras (Bonzio–Pra Baldi 2024) are built")
    print("  over Plonka sums (their internal weak-Kleene layer is one).")
    plonka_dead = 0
    for name, lhs, rhs in REGULAR_BOOLEAN_IDENTITIES:
        cex = [p for p in VALUES if lhs(p) != rhs(p)]
        status = f"✗ FAILS at p={cex[0]}" if cex else "✓ holds"
        if cex:
            plonka_dead += 1
        print(f"  regular identity: {name:34s} {status}")
    if plonka_dead:
        print("  ⟹ A VIOLATES regular Boolean identities — A is NOT a")
        print("  Plonka sum of Boolean algebras. The greedy quasivariety is")
        print("  structurally FOREIGN to the weak-Kleene/BCA landscape:")
        print("  kinship in expressive power (E14), divorce in structure.")

    print("\n### Verdict for the curator")
    print("  The ground holds ore: a simple 3-element generator with a")
    print("  unique Boolean subalgebra, a fully described clone, and a")
    print("  measured NON-Plonka signature where the nearest literature")
    print("  (BCA) is Plonka-based. A separate paper would need: the")
    print("  axiomatization of Q(A) by quasi-identities, its subquasi-")
    print("  variety lattice, and the representation theorem replacing")
    print("  Plonka sums. That is genuine algebra — paper-sized, as")
    print("  suspected; the recon is done and the instrument is ready.")
    if not (len(subs) == 2 and chain3 and len(c1) == 9 and len(c2) == 514
            and plonka_dead >= 1):
        raise SystemExit("RECON MEASUREMENT FAILED — stop.")
