# -*- coding: utf-8 -*-
"""
E23 — Zhegalkin under zero trust: the basis survives, the ring falls.

Zhegalkin's classical theorem: every Boolean function is a polynomial
over GF(2) — a XOR of AND-monomials with the constant 1; the
representation is UNIQUE (multilinear normal form). Two separable
halves: {∧, ⊕, 1} as a complete BASIS, and the GF(2) RING laws that
make the polynomial canonical.

MEASURED here:
  1. THE BASIS SURVIVES ENTIRELY: the clone generated by {∧, ⊕} +
     constants equals the full ZTL clone of E19 — all 514 operations
     (2 projections + all 512 externals), the same closure as the
     canonical basis {¬, ∧, ∨}. Negation is definable verbatim as
     Zhegalkin's x⊕⊤ (their Z-columns coincide cell by cell); ∨, →, ↔
     are all reached — nontrivially, since ⊕ and ∧ return F on ANY
     Z-argument: the closure digs Z out through double-touch terms
     (x∧x-style), which is greediness working for expressiveness.
  2. CHARACTERISTIC 2 SURVIVES: x⊕x ≡ ⊥ holds as a TABLE identity on
     all three values — it is literally the anchor cell xor(Z,Z)=F.
  3. THE RING FALLS, hence no canonical polynomial: the unit law
     x∧⊤ ≡ x dies at Z (gives F — the fallen units of the price
     list), idempotence x∧x ≡ x died in E14 (it is the J_T detector),
     and distributivity of ∧ over ⊕ falls at the cell (T,Z,T)
     (LHS F, RHS T). Multilinear normal forms need all three; the
     normal-form role in ZTL is played by the J-DNF of the external
     layer (E14), not by GF(2) polynomials.

  4. SINGLE-OPERATOR FATES: {∧}+consts cannot make ¬ (the classical
     monotonicity ban survives by restriction) — its clone is 7
     operations — but it BIRTHS the J_T detector (p∧p), a profession
     ∧ does not have classically. And SHEFFER'S STROKE LOSES
     COMPLETENESS: {NAND}+consts stalls at 18 of 514 (¬ reachable,
     the clone not) — the classical champion of one-operator
     completeness does not survive zero trust, while Zhegalkin's
     PAIR does. Completeness, too, is not granted on credit.

Lean twin: lean/ZClone.lean — the negative half by the certificate
method (the 18-table cage, closure as one decide), the positive half
by explicit witness terms; eleven theorems, empty axiom list.

Slogan: Zhegalkin-as-basis moves onto ZTL; Zhegalkin-as-ring stays on
the classical shore.
"""

from itertools import product

from ztl import T, F, Z, VALUES, NOT, AND, OR, IMP, XOR, XNOR, lift2

DOM = list(product(VALUES, repeat=2))            # the 9 input pairs


def tbl(f):
    return tuple(f(x, y) for x, y in DOM)


START = {tbl(lambda x, y: x), tbl(lambda x, y: y),
         tbl(lambda x, y: T), tbl(lambda x, y: F)}


def close(ops, with_not=False):
    S = set(START)
    frontier = set(S)
    while frontier:
        new = set()
        for a in list(S):
            if with_not:
                t = tuple(NOT(v) for v in a)
                if t not in S:
                    new.add(t)
            for b in list(S):
                if a in frontier or b in frontier:
                    for op in ops:
                        t = tuple(op(a[i], b[i]) for i in range(9))
                        if t not in S:
                            new.add(t)
        S |= new
        frontier = new
    return S


def externals(S):
    return sum(1 for t in S if all(v in (T, F) for v in t))


def main():
    print("=" * 72)
    print("E23: ZHEGALKIN UNDER ZERO TRUST (the basis vs the ring)")
    print("=" * 72)

    zheg = close([AND, XOR])
    canon = close([AND, OR], with_not=True)
    print("\n-- 1. THE BASIS --")
    print(f"  clone of {{∧,⊕}}+consts : {len(zheg)} operations "
          f"({externals(zheg)} external)")
    print(f"  clone of {{¬,∧,∨}}+consts: {len(canon)} operations "
          f"({externals(canon)} external)")
    assert zheg == canon and len(zheg) == 514
    named = [("¬ = x⊕⊤", tuple(NOT(x) for x, y in DOM)),
             ("∨", tbl(OR)), ("→", tbl(IMP)), ("↔", tbl(XNOR))]
    for name, t in named:
        assert t in zheg
        print(f"    {name:8s} reached ✓")
    print("  → THE ZHEGALKIN BASIS SURVIVES ENTIRELY: {∧,⊕}+consts")
    print("    generates the full E19 clone, negation verbatim as x⊕⊤.")

    print("\n-- 2. CHARACTERISTIC 2 --")
    assert all(XOR(v, v) == F for v in VALUES)
    print("  x⊕x ≡ ⊥ on all three values ✓ (the anchor cell xor(Z,Z)=F)")

    print("\n-- 3. THE RING FALLS --")
    unit = all(AND(v, T) == v for v in VALUES)
    idem = all(AND(v, v) == v for v in VALUES)
    dist = all(AND(a, XOR(b, c)) == XOR(AND(a, b), AND(a, c))
               for a in VALUES for b in VALUES for c in VALUES)
    print(f"  unit x∧⊤ ≡ x        : {unit}  (at Z: {AND(Z, T)})")
    print(f"  idempotence x∧x ≡ x : {idem}  (at Z: {AND(Z, Z)} — the J_T"
          " detector)")
    print(f"  ∧ distributes over ⊕: {dist}  (cell (T,Z,T): "
          f"LHS {AND(T, XOR(Z, T))}, RHS {XOR(AND(T, Z), AND(T, T))})")
    assert not unit and not idem and not dist
    print("  → no multilinear canonical form: Zhegalkin-as-ring stays on")
    print("    the classical shore; the normal-form job in ZTL belongs to")
    print("    the J-DNF of the external layer (E14).")

    print("\n-- 4. SINGLE-OPERATOR FATES --")
    and_clone = close([AND])
    NAND = lift2(lambda a, b: F if (a == T and b == T) else T)
    NOR = lift2(lambda a, b: T if (a == F and b == F) else F)
    nand_clone = close([NAND])
    nor_clone = close([NOR])
    not_tbl = tuple(NOT(x) for x, y in DOM)
    jt_tbl = tuple(AND(x, x) for x, y in DOM)
    nor_diag = tuple(NOR(x, x) for x, y in DOM)
    print(f"  {{∧}}+consts  : clone {len(and_clone)} — ¬ reachable: "
          f"{not_tbl in and_clone}; J_T (p∧p) reachable: "
          f"{jt_tbl in and_clone}")
    print(f"  {{NAND}}+consts: clone {len(nand_clone)} of 514 — ¬ reachable: "
          f"{not_tbl in nand_clone}")
    print(f"  {{NOR}}+consts : clone {len(nor_clone)} of 514 — ¬ reachable: "
          f"{not_tbl in nor_clone}; NOR(p,p) = ¬p verbatim: "
          f"{nor_diag == not_tbl}")
    NIMPL = lift2(lambda a, b: T if (a == T and b == F) else F)
    nimpl_clone = close([NIMPL])
    print(f"  {{↛}}+consts  : clone {len(nimpl_clone)} of 514 — complete alone")
    assert not_tbl not in and_clone and jt_tbl in and_clone
    assert not_tbl in nand_clone and len(nand_clone) < 514
    assert nor_diag == not_tbl and len(nor_clone) == len(nand_clone)
    assert len(nimpl_clone) == 514

    print("\n-- 5. THE CENSUS OF SIXTEEN (corrects §4's former 'sole') --")
    # All 16 binary Boolean kernels, lifted; bits over (TT, TF, FT, FF).
    kernels = {(0,0,0,0): "⊥", (1,1,1,1): "⊤", (1,1,0,0): "p",
               (0,0,1,1): "¬p", (1,0,1,0): "q", (0,1,0,1): "¬q",
               (1,0,0,0): "∧", (1,1,1,0): "∨", (0,1,1,0): "⊕",
               (1,0,0,1): "↔", (0,1,1,1): "NAND", (0,0,0,1): "NOR",
               (0,1,0,0): "↛", (0,0,1,0): "↚",
               (1,1,0,1): "impl-shaped", (1,0,1,1): "impl-shaped'"}
    complete, fallen = [], []
    for bits, name in kernels.items():
        cells = {(T,T): bits[0], (T,F): bits[1], (F,T): bits[2],
                 (F,F): bits[3]}
        op = lift2(lambda a, b, c=cells: T if c[(a, b)] else F)
        n = len(close([op]))
        noncomm = bits[1] != bits[2]
        dep_q = bits[0] != bits[1] or bits[2] != bits[3]
        dep_p = bits[0] != bits[2] or bits[1] != bits[3]
        essential = dep_p and dep_q
        (complete if n == 514 else fallen).append((name, n, noncomm))
        # THE LAW: solo-complete ⟺ essentially binary AND non-commutative
        assert (n == 514) == (essential and noncomm), (name, n)
    print(f"  complete alone ({len(complete)}): "
          + ", ".join(f"{nm}" for nm, _, _ in complete))
    print(f"  fallen ({len(fallen)}): "
          + ", ".join(f"{nm}({n})" for nm, n, _ in fallen))
    print("  → THE CENSUS LAW, total over all sixteen kernels:")
    print("    a lifted binary connective is COMPLETE ALONE (with consts)")
    print("    ⟺ its kernel is ESSENTIALLY BINARY and NON-COMMUTATIVE. The four")
    print("    directional connectives (both implications, both")
    print("    abjunctions) survive; every commutative kernel falls —")
    print("    including both classical solo champions. Directionality,")
    print("    not mark-killing, is the true mechanism; the earlier")
    print("    'sole surviving solo basis' wording was an overclaim")
    print("    beyond the four measured candidates — corrected here.")
    print("  → (the once-conjectured mechanism 'must negate and kill the")
    print("    mark' is CORRECTED by §5: lifted implication mints T over")
    print("    Z-cells yet is complete — directionality is the law.)")
    print("  → ∧ alone cannot make ¬ (the monotonicity ban survives by")
    print("    classical restriction) yet births the J_T detector; and")
    print("    SHEFFER'S STROKE LOSES COMPLETENESS under zero trust —")
    print("    the one-operator champion stalls while Zhegalkin's pair")
    print("    generates everything. Completeness is not granted on credit.")

    print("\n" + "=" * 72)
    print("VERDICT: Zhegalkin-as-basis MOVES (clone equality 514 = 514);")
    print("Zhegalkin-as-ring FALLS (unit, idempotence, distributivity);")
    print("the CENSUS LAW: a lifted connective is complete alone iff its")
    print("kernel is essentially binary and non-commutative — the four")
    print("directional connectives survive (both implications, both")
    print("abjunctions), every commutative kernel falls, including both")
    print("classical solo champions (18 of 514); lone ∧ births J_T.")
    print("=" * 72)


if __name__ == "__main__":
    main()
