# -*- coding: utf-8 -*-
"""
list_theorems — dump every ZTL theorem to a plain text file.

The theorems are already crystal: each is machine-checked by the Lean 4
kernel on the EMPTY axiom list, so it is immutable by nature — a proved
theorem does not change. This is why "freezing a subset" needs no freeze
mechanism: the theorems ARE the frozen contract. This script writes the
full list (grouped by module, in source order) so that a consumer can pick
exactly the theorems its conformance depends on.

Reuses the audit's own extraction so the list matches the audited count.

Run:  python3 inventory/list_theorems.py   →   writes ZTL-theorems.txt
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, _HERE)

import axiom_audit as aa                                          # noqa: E402

# one line per module, so a reader can pick without opening the source
DESC = {
    "ZTL": "the core: T/F/Z, the greedy zero-trust lift, the connectives, "
           "the anchor cells, and greediness (Z never values a compound)",
    "TableauCert": "the signed-tableau proof engine on {¬,∧,∨}: closure ⟺ "
                   "unsatisfiability, ⊢ ⟺ ⊨",
    "TableauCertN": "the native engine with →/⊕/↔ and engines-agree",
    "ZSets": "sets with unverified elements (membership, {Z} vs {Z,Z})",
    "Facts": "quantifiers (dom 2), the periods, Curry, parity, Yablo-3, the "
             "crocodile",
    "ZAlgebra": "algebraizability (Blok–Pigozzi), the two-way external DDT, "
                "Craig interpolation, structurality",
    "ZSequent": "the sequent calculus and semantic cut admissibility",
    "ZQuant": "the quantifier layer",
    "ZGround": "grounding",
    "ZExped": "the expeditions (fixed points, the paradox range)",
    "ZClone": "the clone / single-operator completeness census of the sixteen "
              "connectives (Finn's external-Bochvar landscape)",
    "ZTime": "logical time: the warranty ladder as temporal quantifiers "
             "(now / at every ending / always on every path)",
    "Contextuality": "the Mermin / GHZ contextuality witnesses",
    "EpochBoundary": "the Epoch Boundary Theorem (a verdict invariant across "
                     "unrestricted epoch crossing is constant)",
    "JunctionWitness": "the PSSL junction witness",
    "QuantumWitness": "the MO2 quantum pole (load-bearing for PSSL)",
    "Frame": "the incompatibility mini-theorems (the fallen laws as a frame)",
    "Signature": "the signature: ¬¬p ⊨ p separates ZTL from any "
                 "involutive-negation matrix; the broken involution ¬¬Z = T",
    "ZEq": "first-order identity: reflexivity earned (Z on an unverified "
           "reference), Leibniz salva-veritate-not-salva-Z",
    "ZDesc": "free logic + definite descriptions: a non-denoting term takes "
             "the mark; existence = earned self-identity",
    "ZEps": "Hilbert's ε (indefinite descriptions): denotes iff a witness is "
            "earned (the ε–∃ bridge)",
}


def main():
    targets = aa.build_targets()
    out = []
    out.append("ZTL — the theorem inventory")
    out.append("=" * 60)
    out.append("")
    out.append("Every theorem below is machine-checked by the Lean 4 kernel")
    out.append("on the EMPTY axiom list (no Classical.choice, no Quot.sound,")
    out.append("not even propext — pure computation). A proved theorem does")
    out.append("not change, so this list is already frozen: it IS the")
    out.append("contract. Pick the subset your conformance depends on.")
    out.append("")
    out.append("Generated by inventory/list_theorems.py; the count matches")
    out.append("inventory/axiom_audit.py, which re-checks every line in CI.")
    out.append("")

    total = 0
    per_module = []
    for m in targets:
        names = aa.theorem_names(m)
        total += len(names)
        block = []
        head = f"## {m}.lean  ({len(names)})"
        if m in DESC:
            head += f"\n     — {DESC[m]}"
        block.append(head)
        for n in names:
            block.append(f"    {n}")
        block.append("")
        per_module.append("\n".join(block))

    out.insert(3, f"{total} theorems across {len(targets)} modules, "
                  f"all on the empty axiom list.\n")
    out.append("")
    out.extend(per_module)

    path = os.path.join(_ROOT, "ZTL-theorems.txt")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {path}: {total} theorems across {len(targets)} modules")


if __name__ == "__main__":
    main()
