name = "ztl"
defaultTargets = ["ZTL", "TableauCert", "TableauCertN", "ZSets", "Facts", "ZAlgebra", "ZSequent", "ZQuant"]

[[lean_lib]]
name = "ZTL"

[[lean_lib]]
name = "TableauCert"

[[lean_lib]]
name = "TableauCertN"

[[lean_lib]]
name = "ZSets"

[[lean_lib]]
name = "Facts"

[[lean_lib]]
name = "ZAlgebra"

[[lean_lib]]
name = "ZSequent"

[[lean_lib]]
name = "ZQuant"
