/-!
# ZTL — Zero-Trust Logic: the machine-checked core

Values T/F (verdicts are two-valued) + the input mark Z; the generating
principle "truth is not granted on credit":
a connective returns T only if T is forced under every classical
reading of Z. All connectives are GENERATED by the lift
(`lift1`/`lift2`) — the tables are not postulated but computed; the
anchor cells are proven as theorems.

VR discipline: `#print axioms` at the end of the file — the whole
corpus must stand on the empty axiom list (pure enumeration, `decide`).
-/

inductive V where
  | T
  | F
  | Z
deriving DecidableEq, Repr

namespace V

/-- Classical readings of a value: Z reads both as truth and as falsehood. -/
def subs : V → List Bool
  | T => [true]
  | F => [false]
  | Z => [true, false]

/-- Lift of a unary classical connective: T only if T is forced
under every reading. -/
def lift1 (f : Bool → Bool) (x : V) : V :=
  if (subs x).all (fun a => f a) then T else F

/-- Lift of a binary classical connective (each occurrence of Z independent). -/
def lift2 (f : Bool → Bool → Bool) (x y : V) : V :=
  if (subs x).all (fun a => (subs y).all (fun b => f a b)) then T else F

def znot  : V → V     := lift1 (fun a => !a)
def zand  : V → V → V := lift2 (fun a b => a && b)
def zor   : V → V → V := lift2 (fun a b => a || b)
def zimp  : V → V → V := lift2 (fun a b => !a || b)
def zxor  : V → V → V := lift2 (fun a b => a != b)
def zxnor : V → V → V := lift2 (fun a b => a == b)

/-- The quarantine detector, expressible inside the language: isZ x = ¬(x↔x). -/
def isZ (x : V) : V := znot (zxnor x x)

/-- Enumeration of the three values is decidable — every `decide` below lives on this. -/
instance (p : V → Prop) [DecidablePred p] : Decidable (∀ x : V, p x) :=
  decidable_of_iff (p T ∧ p F ∧ p Z)
    ⟨fun ⟨hT, hF, hZ⟩ x => by cases x <;> assumption,
     fun h => ⟨h T, h F, h Z⟩⟩

/-! ## The anchor cells (design axioms of 2026-07-10) — now theorems -/

theorem ax_not_Z    : znot Z = F := by decide
theorem ax_notnot_Z : znot (znot Z) = T := by decide
theorem ax_xnor_ZZ  : zxnor Z Z = F := by decide
theorem ax_xnor_ZT  : zxnor Z T = F := by decide
theorem ax_xor_ZZ   : zxor Z Z = F := by decide
theorem ax_xor_ZF   : zxor Z F = F := by decide
theorem ax_xor_ZT   : zxor Z T = F := by decide

/-! ## The greediness theorem: compound formulas are classical, Z lives only on atoms -/

theorem lift1_classical (f : Bool → Bool) (x : V) :
    lift1 f x = T ∨ lift1 f x = F := by
  unfold lift1; split
  · exact Or.inl rfl
  · exact Or.inr rfl

theorem lift2_classical (f : Bool → Bool → Bool) (x y : V) :
    lift2 f x y = T ∨ lift2 f x y = F := by
  unfold lift2; split
  · exact Or.inl rfl
  · exact Or.inr rfl

/-! ## Alive laws (12) -/

theorem imp_def   : ∀ p q, zimp p q = zor (znot p) q := by decide
theorem xor_def   : ∀ p q, zxor p q = zor (zand p (znot q)) (zand (znot p) q) := by decide
theorem xnor_def  : ∀ p q, zxnor p q = zor (zand p q) (zand (znot p) (znot q)) := by decide
theorem xnor_imps : ∀ p q, zxnor p q = zand (zimp p q) (zimp q p) := by decide
theorem and_comm' : ∀ p q, zand p q = zand q p := by decide
theorem or_comm'  : ∀ p q, zor p q = zor q p := by decide
theorem and_assoc' : ∀ p q r, zand (zand p q) r = zand p (zand q r) := by decide
theorem or_assoc'  : ∀ p q r, zor (zor p q) r = zor p (zor q r) := by decide
theorem and_distrib : ∀ p q r, zand p (zor q r) = zor (zand p q) (zand p r) := by decide
theorem or_distrib  : ∀ p q r, zor p (zand q r) = zand (zor p q) (zor p r) := by decide
theorem no_contradiction : ∀ p, znot (zand p (znot p)) = T := by decide
theorem imp_trans_law : ∀ p q r,
    zimp (zand (zimp p q) (zimp q r)) (zimp p r) = T := by decide

/-- Modus ponens, semantic: earned truth is transported. -/
theorem modus_ponens : ∀ p q : V, p = T → zimp p q = T → q = T := by decide

/-! ## Fallen laws (14) — the manifesto, machine-certified -/

theorem double_neg_fails : ¬ ∀ p, znot (znot p) = p := by decide
theorem deMorgan1_fails : ¬ ∀ p q, znot (zand p q) = zor (znot p) (znot q) := by decide
theorem deMorgan2_fails : ¬ ∀ p q, znot (zor p q) = zand (znot p) (znot q) := by decide
theorem contraposition_fails : ¬ ∀ p q, zimp p q = zimp (znot q) (znot p) := by decide
theorem xor_as_not_xnor_fails : ¬ ∀ p q, zxor p q = znot (zxnor p q) := by decide
theorem and_idem_fails : ¬ ∀ p, zand p p = p := by decide
theorem or_idem_fails : ¬ ∀ p, zor p p = p := by decide
theorem absorption_fails : ¬ ∀ p q, zand p (zor p q) = p := by decide
theorem and_true_fails : ¬ ∀ p, zand p T = p := by decide
theorem or_false_fails : ¬ ∀ p, zor p F = p := by decide
theorem lem_fails : ¬ ∀ p, zor p (znot p) = T := by decide
theorem imp_refl_fails : ¬ ∀ p, zimp p p = T := by decide
theorem peirce_fails : ¬ ∀ p q, zimp (zimp (zimp p q) p) p = T := by decide
theorem k_axiom_fails : ¬ ∀ p q, zimp q (zimp p q) = T := by decide

/-! ## Mini-theorems of the frame (preprint §3.5) -/

/-- Negation has no fixed point — the liar is homeless in the tables;
the quarantine flag is irremovable. -/
theorem liar_homeless : ∀ v : V, znot v ≠ v := by decide

/-- Quarantine is detectable from inside (the avenger's door — the price of fork 3). -/
theorem isZ_detects : isZ Z = T ∧ isZ T = F ∧ isZ F = F := by decide

/-- The rules-versus-laws split in one point: the rule p⊨p is trivial,
while the law ⊨p→p fell — the deduction theorem is one-directional. -/
theorem dt_one_way : zimp Z Z = F := by decide

/-- Quantifiers on the domain {a}: ∀ = a strict conjunction of instances. -/
def allq (v : V) : V := if v = T then T else F
def exq  (v : V) : V := if v = T then T else F

/-- The quantifier asymmetry: UI is alive as a LAW (⊨ ∀yP→P(a)) —
the universal is earned, spend it freely... -/
theorem ui_law : ∀ v : V, zimp (allq v) v = T := by decide

/-- ...while EG as a law fell (P(a)=Z yields no ∃): a strict witness is mandatory. -/
theorem eg_law_fails : ¬ ∀ v : V, zimp v (exq v) = T := by decide

/-! ## Part II: entailment, two registers, the fixed point -/

/-! ### Inference rules as entailments (designated value {T}) -/

theorem rule_modus_tollens : ∀ p q, zimp p q = T → znot q = T → znot p = T := by decide
theorem rule_contraposition : ∀ p q, zimp p q = T → zimp (znot q) (znot p) = T := by decide
theorem rule_disj_syllogism : ∀ p q, zor p q = T → znot p = T → q = T := by decide
theorem rule_and_intro : ∀ p q, p = T → q = T → zand p q = T := by decide
theorem rule_and_elim : ∀ p q, zand p q = T → p = T := by decide
theorem rule_or_intro : ∀ p q, p = T → zor p q = T := by decide
theorem rule_dn_intro : ∀ p, p = T → znot (znot p) = T := by decide
theorem rule_transitivity : ∀ p q r, zimp p q = T → zimp q r = T → zimp p r = T := by decide
theorem rule_K : ∀ p q, q = T → zimp p q = T := by decide
theorem rule_explosion : ∀ p q, p = T → znot p = T → q = T := by decide
theorem rule_resolution : ∀ p q r, zor p q = T → zor (znot p) r = T → zor q r = T := by decide

/-- A fallen rule: ¬¬-elimination (Z leaks through double negation). -/
theorem rule_dn_elim_fails : ¬ ∀ p, znot (znot p) = T → p = T := by decide
/-- A fallen rule: tautology in the conclusion (a fresh atom earns no T). -/
theorem rule_taut_concl_fails : ¬ ∀ p q, p = T → zor q (znot q) = T := by decide

/-! The rules-versus-laws split: contraposition-as-a-RULE is alive
(rule_contraposition), contraposition-as-a-LAW fell
(contraposition_fails). Classical logic glues them by the deduction
theorem; in ZTL it is one-directional (dt_one_way: zimp Z Z = F while
p⊨p is trivial). -/

/-! ### Paracompleteness, not paraconsistency -/

theorem no_gluts : ∀ p, ¬(p = T ∧ znot p = T) := by decide

/-! ### The lazy register (strong Kleene) and the information order

The symbol Z is reused positionally here: inside the lazy iteration it
plays the solver's phase N ("not yet computed" — preprint §10), not
the input mark. The role differs, not the alphabet; the greedy
register is what forbids the status from becoming a value of
assertions. -/

def knot : V → V
  | T => F | F => T | Z => Z

-- Non-overlapping matches: an overlapping wildcard row pulls propext
-- in through the compiled matcher (measured; same pitfall as eqAtom).
def kand : V → V → V
  | T, T => T | T, F => F | T, Z => Z
  | F, T => F | F, F => F | F, Z => F
  | Z, T => Z | Z, F => F | Z, Z => Z

def kor : V → V → V
  | T, T => T | T, F => T | T, Z => T
  | F, T => T | F, F => F | F, Z => Z
  | Z, T => T | Z, F => Z | Z, Z => Z

/-- The information order: Z ⊑ everything, T and F incomparable. -/
def leqb (a b : V) : Bool := a == b || a == Z

theorem kleene_not_monotone : ∀ a b, leqb a b = true →
    leqb (knot a) (knot b) = true := by decide
theorem kleene_and_monotone : ∀ a b c d, leqb a c = true → leqb b d = true →
    leqb (kand a b) (kand c d) = true := by decide
theorem kleene_or_monotone : ∀ a b c d, leqb a c = true → leqb b d = true →
    leqb (kor a b) (kor c d) = true := by decide

/-- The greedy register is non-monotone — the Knaster–Tarski argument does not apply. -/
theorem eager_and_not_monotone : ¬ ∀ a b c d, leqb a c = true →
    leqb b d = true → leqb (zand a b) (zand c d) = true := by decide
theorem eager_not_not_monotone : ¬ ∀ a b, leqb a b = true →
    leqb (znot a) (znot b) = true := by decide

/-! ### The liar, the carousel, the avenger — fixed points -/

/-- The liar finds a home in the lazy register... -/
theorem liar_kleene_home : knot Z = Z := rfl

/-- ...while Jourdain's carousel has no greedy model at any values:
the demand v(A)=v(B) and v(B)=v(¬A) is unsatisfiable (all 9 pairs). -/
theorem carousel_no_model : ∀ a b : V, ¬(a = b ∧ b = znot a) := by decide

/-- Lazy grounding of the carousel: (Z,Z) is a fixed point. -/
theorem carousel_kleene_fp : (Z : V) = Z ∧ knot Z = Z := ⟨rfl, rfl⟩

/-- The avenger's bullet, computed: the content μ = ¬Tr(μ) ∨ isZ(μ) at
grounded μ=Z greedily gives T — while the sentence is denied truth. -/
theorem revenge_bullet : zor (znot Z) (isZ Z) = T := by decide

/-! ## Part III: the formula language and the tableau pillars

The debt of honor on the calculus: the two load-bearing pillars of the
signed tableaux, verbatim. Pillar 1 — greediness over the whole formula
language (not a finite battery). Pillar 2 — exact preimage coverage by
each rule, for arbitrary subformula values (⟺, both directions). The
only thing left unformalized is the textbook glue (the engine's
induction on formula size) — Hähnle, standard. -/

inductive Fm where
  | atom : Nat → Fm
  | neg  : Fm → Fm
  | conj : Fm → Fm → Fm
  | disj : Fm → Fm → Fm
  | imp  : Fm → Fm → Fm
  | xor  : Fm → Fm → Fm
  | xnor : Fm → Fm → Fm
  | top  : Fm
  | bot  : Fm

def evalF (v : Nat → V) : Fm → V
  | .atom n   => v n
  | .top      => T
  | .bot      => F
  | .neg φ    => znot (evalF v φ)
  | .conj φ ψ => zand (evalF v φ) (evalF v ψ)
  | .disj φ ψ => zor (evalF v φ) (evalF v ψ)
  | .imp φ ψ  => zimp (evalF v φ) (evalF v ψ)
  | .xor φ ψ  => zxor (evalF v φ) (evalF v ψ)
  | .xnor φ ψ => zxnor (evalF v φ) (evalF v ψ)

/-- Pillar 1. Greediness over the whole language: every COMPOUND formula
is classical under every valuation — Z lives only on atoms. -/
theorem evalF_classical (v : Nat → V) :
    ∀ φ : Fm, (∃ n, φ = .atom n) ∨ evalF v φ = T ∨ evalF v φ = F := by
  intro φ
  cases φ with
  | atom n   => exact Or.inl ⟨n, rfl⟩
  | neg φ    => exact Or.inr (lift1_classical _ _)
  | conj φ ψ => exact Or.inr (lift2_classical _ _ _)
  | disj φ ψ => exact Or.inr (lift2_classical _ _ _)
  | imp φ ψ  => exact Or.inr (lift2_classical _ _ _)
  | xor φ ψ  => exact Or.inr (lift2_classical _ _ _)
  | xnor φ ψ => exact Or.inr (lift2_classical _ _ _)
  | top => exact Or.inr (Or.inl rfl)
  | bot => exact Or.inr (Or.inr rfl)

/-! Pillar 2. Preimage coverage: every tableau rule is ⟺-exact.
Signs: strict T/F; weak P = {T,Z} ("possibly T"), N = {F,Z}. -/

theorem cover_not_T  : ∀ a : V, znot a = T ↔ a = F := by decide
theorem cover_not_F  : ∀ a : V, znot a = F ↔ (a = T ∨ a = Z) := by decide
theorem cover_and_T  : ∀ a b : V, zand a b = T ↔ (a = T ∧ b = T) := by decide
theorem cover_and_F  : ∀ a b : V,
    zand a b = F ↔ ((a = F ∨ a = Z) ∨ (b = F ∨ b = Z)) := by decide
theorem cover_or_T   : ∀ a b : V, zor a b = T ↔ (a = T ∨ b = T) := by decide
theorem cover_or_F   : ∀ a b : V,
    zor a b = F ↔ ((a = F ∨ a = Z) ∧ (b = F ∨ b = Z)) := by decide
theorem cover_imp_T  : ∀ a b : V, zimp a b = T ↔ (a = F ∨ b = T) := by decide
theorem cover_imp_F  : ∀ a b : V,
    zimp a b = F ↔ ((a = T ∨ a = Z) ∧ (b = F ∨ b = Z)) := by decide
theorem cover_xor_T  : ∀ a b : V,
    zxor a b = T ↔ ((a = T ∧ b = F) ∨ (a = F ∧ b = T)) := by decide
theorem cover_xor_F  : ∀ a b : V,
    zxor a b = F ↔ (((a = T ∨ a = Z) ∧ (b = T ∨ b = Z)) ∨
                    ((a = F ∨ a = Z) ∧ (b = F ∨ b = Z))) := by decide
theorem cover_xnor_T : ∀ a b : V,
    zxnor a b = T ↔ ((a = T ∧ b = T) ∨ (a = F ∧ b = F)) := by decide
theorem cover_xnor_F : ∀ a b : V,
    zxnor a b = F ↔ (((a = T ∨ a = Z) ∧ (b = F ∨ b = Z)) ∨
                     ((a = F ∨ a = Z) ∧ (b = T ∨ b = Z))) := by decide

/-! ## The extensionality divorce (anti-propext, at the object level)

`propext` is the licence "equivalent, hence identical — replace anywhere".
This system refuses the object-level analogue, and the refusal is a theorem:
`p` and `p ∧ p` have the same truth profile (by-consequence equivalent), yet
their tables differ at the mark, and a CONTEXT — the quarantine detector —
separates them.  Equivalence does not buy identity; transport goes by
direction (`Iff.mp`/`Iff.mpr`), never by rewriting.  Hence every `[propext]`
in a meta-proof's tail is the mark of a replacement licence that the object
logic itself does not grant. -/

/-- **Interderivable, yet not the same function.**  Same T-profile; different
tables at `Z`; separated by the `isZ` context.  The object-level refutation
of the replacement-of-equivalents licence — on the empty axiom list. -/
theorem equiv_not_identical :
    (∀ x : V, (zand x x = T) ↔ (x = T)) ∧
    zand Z Z ≠ Z ∧
    isZ (zand Z Z) ≠ isZ Z := by
  refine ⟨?_, by decide, by decide⟩
  decide

#print axioms kand
#print axioms kor
#print axioms modus_ponens
#print axioms lem_fails
#print axioms liar_homeless
#print axioms lift2_classical
#print axioms rule_contraposition
#print axioms eager_and_not_monotone
#print axioms carousel_no_model
#print axioms revenge_bullet
#print axioms evalF_classical
#print axioms cover_imp_F
#print axioms equiv_not_identical

end V
